# Generated by Django 3.2.16 on 2023-01-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0005_auto_20230110_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
