# Generated by Django 3.2.16 on 2023-01-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0006_alter_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
